### ISSUE TITLE
PATH Editing Instructions

### ISSUE THREAD

**Issue by RustyDawwwgg** [dbaumgarten/yodk#111]
Please add instructions on editing the PATH for supported OS (don't assume everyone already knows how to do this).

Example:
https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

**Comment by dbaumgarten** [comment]
I guess thats possible, but why?
Editing the path is not necessary for the majority of users. They just use vscode and everything works out of the box.

Fiddeling with the PATH only becomes helpful when using the cli standalone. (And people using clis usually have a bit of backgound-knowledge.)

What are you trying to do that requires you to edit your PATH?

**Comment by RustyDawwwgg** [comment]
My goal here is to NOT depend on vscode for use with yodk. I spent a number of hours migrating all of my projects out of vscode for a variety of reasons and I do not intend to go back just for Starbase projects. I have no issues with using the cli myself and the suggestion was purely to help those who are less knowledgeable.

**Comment by dbaumgarten** [comment]
Done
