### ISSUE TITLE
Atom Extension

### ISSUE THREAD

**Issue by RustyDawwwgg** [dbaumgarten/yodk#112]
**Is your feature request related to a problem? Please describe.**
YOLOL-related packages are non-existent in Atom

**Describe the solution you'd like**
Syntax highlighting would be highly appreciated, along with whatever else you'd like to add

**Describe alternatives you've considered**
None - all of my projects are now finally migrated over to Atom and I do not wish to switch back just for YOLOL projects

**Additional context**
https://atom.io/

**Comment by dbaumgarten** [comment]
This is pretty similar to #73 .

I do not plan to create an atom extension for this.
But anyone who is really interested in this, can do it himself.

By using yodk's language-server implementation and the texmate-grammars used for syntax-highlighting this should be relatively simple.
