### ISSUE TITLE
integer comparison bug

### ISSUE THREAD

**Issue by lizelive** [dbaumgarten/yodk#116]
**Describe the bug**
i think its a integer comparison bug

**Example code**
`a="1" :d=5*(a>4) :d+=2*(a>:d+1) :d+=a>:d :d+=a>:d goto1`
should return 1 but it returns 4

```
a=1 b=2
goto 1
```

**Ingame results**
1
**Yodk results**
4
**Additional context**
parsing strings

**Comment by dbaumgarten** [comment]
Closed due to inactivity
