### ISSUE TITLE
auto typing

### ISSUE THREAD

**Issue by tylerv602** [dbaumgarten/yodk#118]
**Describe the bug**
the auto typing feature in the vscode is not working in starbase or other apps

**To Reproduce**

**Expected behavior**
auto type to auto type my .yolol in to starbase yolol chip

**Example Code/Screenshots**
If applicable, add examples or screenshots to help explain your problem.

**Platform:**
 - OS: windows
 - Version of vscode-yolol latest

**Additional context**

**Comment by dbaumgarten** [comment]
Are you running Starbase "as Administrator"?
If so, you need to also run vscode as administrator (or stop running Starbase as such).
