### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by GamerDNA** [dbaumgarten/yodk#123]
Would it be possible to get a version of the YOLOL/YODK that can be imported into Visual Studio 2019.  Not sure why VSCode will not run on my machine without trying to mess up my VS2019 install and projects.

I found this link that may be of interest:
https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by dbaumgarten** [comment]
I think you are confusing something here.
VScode and Visual Studio 20XX are two completely seperate things. They have nothing in common, except for the name-similarity.

It's not possible to support Visual Studio with a vscode-extension.
And vscode should in no way interfere with your Visual Studio.
