### ISSUE TITLE
Allow insertion into SSC chips

### ISSUE THREAD

**Issue by MyrddinE** [dbaumgarten/yodk#39]
It's currently not possible to auto-insert into the SSC, due to the different interface. The SSC chip editing window requires two keystrokes to move to the next line, rather than one.

**Comment by dbaumgarten** [comment]
I just publiched v0.0.32, which contains experimental support for auto-typing inside the SSC.
Once somebody confirms that it is actually working, this issue can be closed.

**Comment by dbaumgarten** [comment]
Unfortunately it does not seem to work...

**Comment by dbaumgarten** [comment]
SSC auto-type seems to work for now. Closed.
