### ISSUE TITLE
Automatically open compiled file upon compilation (VS Code)

### ISSUE THREAD

**Issue by Woccz** [dbaumgarten/yodk#56]
I think most times you compile a file, you have finished editing it, and therefore either want to view the compiled file or click away to another file. 
Due to this, automatically opening the compiled file in the editor saves time in case 1, and in case 2, it does not add any complexity.

If you think this is a good idea, and relatively simple to implement, then I think it would be a good addition.

Thank you.

**Comment by dbaumgarten** [comment]
Should be relatively easy to implement.
But I am not sure if I really want something to mess with my opened files and tabs.

I guess I will try to implemented and see how it feels. If it feels more helpfull than annoying, I will add it (maybe with an option to turn that off)

**Comment by Woccz** [comment]
Ok, thank you.

**Comment by dbaumgarten** [comment]
Vscode will now automatically open and focus compiled/optimized files, unless they are already visible.
The behavior can be disabled in the vscode-settings.

**Comment by dbaumgarten** [comment]
Published as part of v0.1.4
