### ISSUE TITLE
Colour 'define'd expressions differently from variables (VS Code)

### ISSUE THREAD

**Issue by Woccz** [dbaumgarten/yodk#58]
I think this would help to reduce possible confusion and unnoticed silent typos.

Thank you.

**Comment by dbaumgarten** [comment]
Thats sadly not possible with vscode.
Syntax-highlighting happens purely clientside using regular expressions.
The component that actually "understands" the language (the languageserver) is not involved in syntax-highlighting at all.

But once the type-system (#48) is added and programmers are forced to properly declare their variables, all identifiers that are not declared variables or definitions can just be treated as errors. That would completely stop silent typos.

**Comment by Woccz** [comment]
That is interesting. How does VSCode recognise yolol specific syntax then? For example, globals with `:` are coloured a darker blue than normal variables; which is really helpful when you miss a `:`.

**Comment by dbaumgarten** [comment]
It is done using regular expressions.
You can tell vscode "everything that matches ```:[a-z]+``` should be color X.

But you can't tell it "everything that appeared in a define-statement before the current position should be colored Y".

**Comment by Woccz** [comment]
Ok. Will this be `Wontfix` closed?

**Comment by dbaumgarten** [comment]
It's more a "can't fix", but yes.
