### ISSUE TITLE
Strip trailing zeros from numbers

### ISSUE THREAD

**Issue by Woccz** [dbaumgarten/yodk#59]
Ideally, all expressions and constants should be evaluated and re-inserted into the code.
![image](https://user-images.githubusercontent.com/44993506/122036315-8aa44580-ce27-11eb-9be3-55f8f1d7f417.png)

**Comment by dbaumgarten** [comment]
That's probably something that won't be needed that often.
But it's also pretty easy to implement and wouldn't hurt.
It could probably just be added to the existing static-expression-optimizer.

**Comment by dbaumgarten** [comment]
Published as part of v0.1.4
