### ISSUE TITLE
Save execution time on overlength loops

### ISSUE THREAD

**Issue by Woccz** [dbaumgarten/yodk#64]
Loops that are overlength and cause `goto1` to be pushed to the next line can be modified to save a tick. This can also work for multi-line loops that push the `goto1` off the end, as long as the `20 ≡ 0 (mod number of lines in the loop)`, otherwise a `goto1` can be used after the last line.

Unoptimised:
![image](https://user-images.githubusercontent.com/44993506/122708315-03842100-d2b0-11eb-9874-b229895af6e7.png)

Optimised:
![image](https://user-images.githubusercontent.com/44993506/122708300-f830f580-d2af-11eb-8b65-b38473ad8ec6.png)

**Comment by dbaumgarten** [comment]
Well, I guess that's true.
But this should be a really rare case, and tbh. it somehow feels really weird to make the compiler do this.

**Comment by Woccz** [comment]
I don't think this case is as rare as you might think, it has happened to me more thsn once. But I do agree that it feels a bit strange 😅.

**Comment by dbaumgarten** [comment]
I have been thinking about this for a while now and came to the conclusion that this is too edge-casey and just feels absolutely weird to do.

If the user absolutely needs to do something that weird, he can still do it by hand.

**Comment by Woccz** [comment]
Okay, I understand and respect your decision, however for loop scripts that are designed to run in as few ticks as possible, a 6 character save can often be all you need to get it down to one tick.
