### ISSUE TITLE
Extend variable naming beyond alphabet

### ISSUE THREAD

**Issue by Woccz** [dbaumgarten/yodk#67]
I'm not sure of all the characters that can and cannot be used, but this would save the variable names tripping to two characters after variable 26.

Thank you.

**Comment by Woccz** [comment]
It is practically impossible to reach 3 character variables in a program.

**Comment by dbaumgarten** [comment]
I think there aren't many chars left here.
Numbers should work, but no as first (or only) character .
Underscores (might?) work, but I am not sure if it can be a variable on its own.

":" Inside a variable may work, but probably not on its own.

I am really not sure what characters besides the current 26 would work as single-char local variables

**Comment by Woccz** [comment]
Anything that canot be used as a first character isn't worth adding, due to the almost certainty of never reaching 3 character locals, with just [a-z].

I previously asked in the CYLON Discord server on this topic, and answers were inconclusive.

**Comment by dbaumgarten** [comment]
For now, 26 characters have to be enough.
