### ISSUE TITLE
NOLOL compilation doesn't seem to respect output parameter

### ISSUE THREAD

**Issue by TheCodedOne** [dbaumgarten/yodk#71]
**Describe the bug**
When compiling NOLOL, the CLI doesn't seem to respect the `-o`/`-out` parameter

**To Reproduce**
1. Make nolol script
2. Compile it with a custom output path

**Expected behavior**
the CLI should output the new file to the path specified.

**Platform:**
 - OS: windows
 - Version of 0.1.6

**Comment by dbaumgarten** [comment]
Seems like you are right.
Funny that nobody noticed that until now.
Will be fixed with the next version, thanks for the bug-report :+1:

**Comment by dbaumgarten** [comment]
Fixed as part of v0.1.7
