### ISSUE TITLE
Add support for copying from game to vscode

### ISSUE THREAD

**Issue by TheCodedOne** [dbaumgarten/yodk#72]
**Is your feature request related to a problem? Please describe.**
I've got a bunch of yolol chips I'd like to edit in a more reasonable manner, but copying 30 yolol chips individually is quite unfun.

Alternatively, a hotkey to simply copy an entire chip into a clipboard would solve this problem too.

**Describe the solution you'd like**
A hotkey similar to vscode -> yolol

**Describe alternatives you've considered**
Copying each line individually while obviously possible, is quite cumbersome at scale

**Additional context**
I'm not sure if it's possible to do it in a nice way, but it'd be nice.

**Comment by dbaumgarten** [comment]
That should be pretty simple to do once I figured out how to interact with the win32 clipboard-api from inside go-code.
Throwing the copied code directly into the currently opened file would be handy, but feels a little bit dangerous.
Just keeping it inside the clipboard for the user to past wherever he likes seems reasonable.

Unfortunately I don't have access to a Windows-PC for the next week or so, so don't expect any immediate progress on that.

**Comment by dbaumgarten** [comment]
Added as part of v0.1.7
