### ISSUE TITLE
VIM plugin

### ISSUE THREAD

**Issue by r3k2** [dbaumgarten/yodk#73]
VIM is my IDE for everything, and tons of engineers use it specially the ones we are on Linux/macOS(darwing) will be nice to have not just a VScode but also a VIM plugin, also lot of people I know we play on Linux not Windows with proton/SteamOS

**Comment by dbaumgarten** [comment]
I love vim like everyone else does, but I don't have any plans to build a vim-plugin.

I will however happily support anyone trying to do this himself.

Somebody already did some work on this: https://github.com/sb-null/vim-yolol
But it looks a little bit abandoned.

Building a vim-plugin using the yodk-binary as backend should be relatively simple. It implements all the basic functions (format, optimize etc.) as cli-commands and also implements the Language Server Protocol.

Sidenote: vscode-yolol should work just fine on Linux and macOS (except for the auto-type feature).

**Comment by r3k2** [comment]
> I love vim like everyone else does, but I don't have any plans to build a vim-plugin.
> 
> I will however happily support anyone trying to do this himself.
> 
> Somebody already did some work on this: https://github.com/sb-null/vim-yolol
> But it looks a little bit abandoned.
> 
> Building a vim-plugin using the yodk-binary as backend should be relatively simple. It implements all the basic functions (format, optimize etc.) as cli-commands and also implements the Language Server Protocol.
> 
> Sidenote: vscode-yolol should work just fine on Linux and macOS (except for the auto-type feature).

Interesting, going to try the vim-yolol see how it works.
Thanks
