### ISSUE TITLE
Visual Studio Code Debugger not shown

### ISSUE THREAD

**Issue by sradola** [dbaumgarten/yodk#74]
When I try to debug, I can't seem to find the option to choose the "YODK Debugger".

**Comment by dbaumgarten** [comment]
Interesting. I just tested it (opened a .yolol file and hit f5) and it started the (correct) debugger right away, without asking me which one.
I guess the vscode-guys changed something so that superflous dialog is not shown anymore.
I will adjust the documentation, thanks for pointing this out.

Just to make sure: The missing dialog is the only issue you have? The debugging itself is working fine?

**Comment by sradola** [comment]
I want to try debug this code:
:LTR01=-5 :LTR02=5 :LTP=0 i=1 if :M_Laser then goto 2 else goto 1 end  
:LTV=0.05 :LaserOn=1
:LTP=-15 if :LTCP01<=-15 and :LTCP02<=-15 then goto4 end goto3
:LTR01+=(i) :LTR02+=(i*-1)
if :LTR01==:LTCR01 and :LTR02==:LTCR02 then goto6 end goto5
:LTP=0 if :LTCP01>=-2 and :LTCP02>=-2 then goto7 end goto6
if :LTR01>=10 and :LTR02<=-10 then :LTV=50 goto12 end
if :M_Laser then goto9 else :LTV=50 :LaserOn=0 goto1 end
:LTR01+=(i) :LTR02+=(i*-1)
if :LTR01==:LTCR01 and :LTR02==:LTCR02 then goto3 end goto10
:LTR01=-5 :LTR02=5 :LaserOn=0
if :LTR01==:LTCR01 and :LTR02==:LTCR02 then goto1 end goto13
I get stuck in the first line and under Global variables I can't see the :M_Laser to manipulate, so that i can get out of the first line.

**Comment by dbaumgarten** [comment]
Variables only show up in that list, after something has been assigned to them at least once.
I guess that is something that could/should be improved.

In the meantime you have a few options:
1. Add :M_Laser=0 to the start of the program

2. Have a second script that sets the variables and debug both at once (the second script would effectively simulate the behaviour of the ship): https://dbaumgarten.github.io/yodk/#/vscode-instructions?id=multiple-scripts-or-tests

3. Write a test.yaml ( https://dbaumgarten.github.io/yodk/#/cli?id=testing ) with the Input-variables you want and debug that test.yaml ( https://dbaumgarten.github.io/yodk/#/vscode-instructions?id=multiple-scripts-or-tests )

**Comment by sradola** [comment]
When I try the option 3.  I get the message Invalid file extension on: test.yaml. Do I need an extra extension?
I have installed the YAML extension from Red Hat.

**Comment by dbaumgarten** [comment]
For debugging a test.yaml, just pressing F5 is sadly not enough. It needs a proper launch-configuration. How that works is described here: https://dbaumgarten.github.io/yodk/#/vscode-instructions?id=multiple-scripts-or-tests

No other extension needs to be installed for this.

**Comment by dbaumgarten** [comment]
As the described issue is now being tracked in #77 I will close this issue.
