### ISSUE TITLE
Add non-assigned to global-variables-debugging

### ISSUE THREAD

**Issue by Syrious** [dbaumgarten/yodk#77]
When debugging for example an if-statement it would be nice to see the global variables in the debug menu. Please check the image. In this short example I can't see :btn in global variables and therefore I can't change its value within the debug session

![Selection_024](https://user-images.githubusercontent.com/8050391/129326976-4cb8ac15-3a11-4760-aba4-43235b7da81b.png)

**Comment by dbaumgarten** [comment]
That's exactly how I intend to solve the problems described in #74 .

The debugger should simply always list all global variables that are used somewhere in the script.

This shouldn't be too difficult to implement. Maybe I can make some progress on this tomorrow.

**Comment by dbaumgarten** [comment]
Added as part of v0.1.7
