### ISSUE TITLE
":" in variable names are considered as an error.

### ISSUE THREAD

**Issue by liperium** [dbaumgarten/yodk#81]
![image](https://user-images.githubusercontent.com/48138387/129463531-ecdba4ea-69f8-494c-a63b-1de88f1527e5.png)
":"+"::::MAT:::"

**Comment by dbaumgarten** [comment]
The fact that ingame-yolol does allow such crazyness really hurts my sould :'(

**Comment by liperium** [comment]
Nice thanks! But yeah, it was for beautifying the thing. Thanks for adding it!

**Comment by dbaumgarten** [comment]
Fixed as part of v0.1.7
