### ISSUE TITLE
I would like multiline comments

### ISSUE THREAD

**Issue by liperium** [dbaumgarten/yodk#82]
See I have a github with my yolol code. And since I need to comment out the user guide when putting it inside the code file. I could use a multi line comment, so that it doesn't print any errors. Maybe something so different people would only know if they know. 
Proposals :
//* *//
##* *##

Thanks, know this is really niche, and I could probably do another file explaining my code instead of putting it in the .yolol. But I figured it must not be too much of a hassle to add.
![image](https://user-images.githubusercontent.com/48138387/129463608-4def593d-7302-42b1-a3cd-25524e9b218b.png)

**Comment by dbaumgarten** [comment]
While doing what you sugessts would stop vscode from displaying errors, code with such multiline-comments would still generate errors ingame. Usually the game would jsut skip invalid lines, but their parser is weird as hell and might do really strange things with partially correct lines.

If you really want usage-instructions inside the code, you will have to use the normal line-comments ( //stuff ).

However, I would suggest putting the instructions into a separate markdown-file. Thats much nicer to read on github then some unhighlighted script-file.
