### ISSUE TITLE
Syntax stuff again <3

### ISSUE THREAD

**Issue by liperium** [dbaumgarten/yodk#84]
This should work 
![image](https://user-images.githubusercontent.com/48138387/129483660-49bb91d7-c78c-4e70-bc70-4f592d0c9bc9.png)
But it's highlighted red :(

Thanks again. Last bug for syntax I've got ;P

**Comment by liperium** [comment]
![image](https://user-images.githubusercontent.com/48138387/129484333-ebc5e78b-4908-4956-81ba-313093f5bf12.png)

**Comment by dbaumgarten** [comment]
Can you provide the full script?
The snippets you are provided are (without any further context) invalid synatx.

**Comment by liperium** [comment]
![image](https://user-images.githubusercontent.com/48138387/129486977-fe560535-00e1-483e-8c1f-973c0a289a00.png)
For example.

**Comment by liperium** [comment]
Works in game too :)

**Comment by dbaumgarten** [comment]
Can you provided any code that prooves that this really works ingame?
Because the rule that "all statements on a line must be separated by spaces" is a pretty fundamental one.
I would be pretty surprised if there is an excpetion specifically for if-statements.
(Given the brokenness of their parser it isn't impossible, but I think its unlikely)

**Comment by dbaumgarten** [comment]
Ok, so i have done my own tests for this.
It seems that a goto immediately after an end does indeed work without a space.
But all other combinations of statements strictly require that space...
This is so damn weird.

**Comment by dbaumgarten** [comment]
Addition: Assignments to global (but not local) variables also seem to be possible without a space after an end.

This is so stupid that I am tempted to just leave everything as it is. Screw that damn absent space.

**Comment by liperium** [comment]
Yeah I can totally understand that, just an easy way to squeeze more stuff ahaha.
