### ISSUE TITLE
Exponential Overflow

### ISSUE THREAD

**Issue by AstraLuma** [dbaumgarten/yodk#85]
**Describe the bug**
Behavior mismatch in exponential overflow

**Example code**
```
:a = 5
:a = 3 ^ 39
:b = 6
:b = 3 ^ 40
:c = 7
:c = 3 ^ 41
```

**Ingame results**
![image](https://user-images.githubusercontent.com/401438/129487839-c3d73ace-a93a-415e-8602-2c1d0ed67d00.png)

**Yodk results**
```
🐚 yodk debug test.nolol
Loaded and paused programs. Enter 'c' to start execution.
>>> c
>>> vars
--Variables--
:a -9223372036854775.808
:b -9223372036854775.808
:c -9223372036854775.808
```

**Comment by dbaumgarten** [comment]
Exponentiation-overflow seems to behave exactly like the game to me.
Are you running this on a basic chip? Basic-chips don't have the ^ operator. In this case it would just skip the line and produce the results you are getting.

**Comment by AstraLuma** [comment]
Oh maybe, I forgot about that.

In which case, yoloxide might have a bug.

**Comment by dbaumgarten** [comment]
Yoloxide is extemely outdated and hasn't received updates on forever.
As my ingame experiments did work out fine, I will just assume that your results were cased by using a basic chip.
Therefore: closed
