### ISSUE TITLE
Implement Auto-Type in Ship Design Workshop

### ISSUE THREAD

**Issue by LTNightshade** [dbaumgarten/yodk#90]
Implement Auto-Type in Ship Design Workshop, please.

Auto-Typing is only working in normal Game, and not in SDW.

**Comment by dbaumgarten** [comment]
Auto-Type is working fine in the ship-designer. But because Starbase is a little weird you have to add <Alt> to the hotkey inside the designer. (Instead of for example Strg+I, press Strg+Alt+I). See here: https://dbaumgarten.github.io/yodk/#/vscode-instructions?id=auto-typing-into-starbase

**Comment by LTNightshade** [comment]
Thanks
