### ISSUE TITLE
AutoType: force stop auto-typing after 20 lines

### ISSUE THREAD

**Issue by Firestar99** [dbaumgarten/yodk#96]
**Is your feature request related to a problem? Please describe.**
Often yolol files have empty lines or comments after the first 20 lines. (yodk optimize doesn't remove them either.) Using Auto-Type also pastes in these lines, making ot go below the yolol chip and do random game input. Tested in SSC.

**Describe the solution you'd like**
Make AutoType always stop after line 20

**Describe alternatives you've considered**
yodk optimize deleting everything after line 20

(I <3 yodk optimize :) finally I can have decent variable names)

**Comment by dbaumgarten** [comment]
Published with v0.1.9.
