### ISSUE TITLE
Global Variable :. (point) doesn't work

### ISSUE THREAD

**Issue by Firestar99** [dbaumgarten/yodk#99]
Just like a special fix was required for ISAN's `_`, but the names `.` `,` `;` also doesn't work. But I don't mind if this ends up as a won't fix.

Interestingly `:` does work, so valid yolol code being `::="hi!"`. 

I wanted to use it as an alternative name so that non-Yolol experts don't accidentally make my Compass and standard ISAN collide. Will ~search for some other variable now~ use `:` now :)

**Comment by dbaumgarten** [comment]
This is already fixed on the develop-branch: https://github.com/dbaumgarten/yodk/commit/3769a586b819faf79a899b636d52c14302394cd9

It will be released with the other changes soon-ish. (Maybe tomorrow)

**Comment by Firestar99** [comment]
Thanks 👍
